# NOTE: To use the commands in this file:
# make name-of-command
# E.g.
# make rust-tool-versions

rust-tool-versions:
	@echo "Here are the versions of Rust tools used in this project:"
	rustc --version	# The compiler
	cargo --version # The package manager
	rustfmt 		# The code formatter
