[project]
name = "syntax-recap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "titanoboa>=0.2.5",
    "vyper>=0.4.0",
]
